# Generated by Django 2.2.16 on 2024-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20240616_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='', help_text='Введите текст названия статьи', verbose_name='Название статьи'),
            preserve_default=False,
        ),
    ]
