# Generated by Django 2.2.16 on 2024-06-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230329_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Одну из доступных.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Выберите группу'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=50000),
        ),
    ]
