# Generated by Django 2.2.16 on 2024-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Введите текст названия статьи', max_length=20, verbose_name='Название статьи'),
        ),
    ]
